[project]
name = "convert-to-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docx2pdf>=0.1.8",
    "fpdf>=1.7.2",
    "img2pdf>=0.5.1",
    "pdf2image>=1.17.0",
    "python-docx>=1.1.2",
    "tk>=0.1.0",
]
